package model;
// Generated 5 juin 2023, 00:50:19 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * Examen generated by hbm2java
 */
public class Examen implements java.io.Serializable {

	private Integer examenId;
	private String type;
	private Date dateExamen;
	private Integer consultationId;

	public Examen() {
	}

	public Examen(String type, Date dateExamen, Integer consultationId) {
		this.type = type;
		this.dateExamen = dateExamen;
		this.consultationId = consultationId;
	}

	public Integer getExamenId() {
		return this.examenId;
	}

	public void setExamenId(Integer examenId) {
		this.examenId = examenId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getDateExamen() {
		return this.dateExamen;
	}

	public void setDateExamen(Date dateExamen) {
		this.dateExamen = dateExamen;
	}

	public Integer getConsultationId() {
		return this.consultationId;
	}

	public void setConsultationId(Integer consultationId) {
		this.consultationId = consultationId;
	}

}
