package model;
// Generated 5 juin 2023, 00:50:19 by Hibernate Tools 4.3.6.Final

/**
 * Medecin generated by hbm2java
 */
public class Medecin implements java.io.Serializable {

	private Integer medecinId;
	private String nom;
	private String specialite;

	public Medecin() {
	}

	public Medecin(String nom, String specialite) {
		this.nom = nom;
		this.specialite = specialite;
	}

	public Integer getMedecinId() {
		return this.medecinId;
	}

	public void setMedecinId(Integer medecinId) {
		this.medecinId = medecinId;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getSpecialite() {
		return this.specialite;
	}

	public void setSpecialite(String specialite) {
		this.specialite = specialite;
	}

}
