package model;
// Generated 5 juin 2023, 00:50:19 by Hibernate Tools 4.3.6.Final

/**
 * Ordonnance generated by hbm2java
 */
public class Ordonnance implements java.io.Serializable {

	private Integer ordonnanceId;
	private Integer consultationId;

	public Ordonnance() {
	}

	public Ordonnance(Integer consultationId) {
		this.consultationId = consultationId;
	}

	public Integer getOrdonnanceId() {
		return this.ordonnanceId;
	}

	public void setOrdonnanceId(Integer ordonnanceId) {
		this.ordonnanceId = ordonnanceId;
	}

	public Integer getConsultationId() {
		return this.consultationId;
	}

	public void setConsultationId(Integer consultationId) {
		this.consultationId = consultationId;
	}

}
