package model;
// Generated 5 juin 2023, 00:50:19 by Hibernate Tools 4.3.6.Final

/**
 * Patient generated by hbm2java
 */
public class Patient implements java.io.Serializable {

	private Integer patientId;
	private String nom;
	private String dateNaissance;
	private String prenoms;
	private String adresse;

	public Patient() {
	}

	public Patient(String nom, String dateNaissance, String prenoms, String adresse) {
		this.nom = nom;
		this.dateNaissance = dateNaissance;
		this.prenoms = prenoms;
		this.adresse = adresse;
	}

	public Integer getPatientId() {
		return this.patientId;
	}

	public void setPatientId(Integer patientId) {
		this.patientId = patientId;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(String dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	public String getPrenoms() {
		return this.prenoms;
	}

	public void setPrenoms(String prenoms) {
		this.prenoms = prenoms;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

}
